src/apps/cars/urls.py
from django.conf.urls import url

from .views import CarsView, ReregistrationView, DeregistrationView, RegistrationView, DocumentView

urlpatterns = [
    url(r'^$', CarsView.as_view()),
    url(r'^reregistration', ReregistrationView.as_view()),
    url(r'^deregistration', DeregistrationView.as_view()),
    url(r'^registration', RegistrationView.as_view()),
    url(r'^document/(?P<doc_id>[0-9a-f]*)', DocumentView.as_view())
]

src/carbase/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

import debug_toolbar


urlpatterns = [
    url(r'^lYq2COXC7cHzWrJ7/', admin.site.urls),
    url(r'^cars/', include('cars.urls')),
    url(r'^pki/', include('pki.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^controller/', include('controller.urls')),
    url(r'^numberplates/', include('numberplates.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html"))
]

if settings.DEBUG:
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/apps/cars/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.template import Context, Template
from django.conf import settings

import gridfs
from pymongo import MongoClient


def pay_by_id(product_id):
    if product_id.startswith('tax'):
        tax = Tax.objects.get(id=product_id[3:])
        tax.is_paid = True
        tax.save()
    elif product_id.startswith('fine'):
        fine = Fine.objects.get(id=product_id[4:])
        fine.is_paid = True
        fine.save()
    elif product_id.startswith('reg'):
        reg = Reregistration.objects.get(id=product_id[3:])
        reg.is_paid = True
        reg.save()


class AgreementTemplate(models.Model):
    ''' Шаблон договора '''
    template = models.TextField()
    owner = models.CharField(max_length=22, null=True, blank=True)
    is_selected = models.BooleanField()
    is_active = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    display_name = models.CharField(max_length=64, null=True, blank=True)

    def __str__(self):
        return self.display_name if self.display_name else ''


class Agreement(models.Model):
    ''' Каждый конкретный экземпляр договора '''
    template = models.ForeignKey(AgreementTemplate)
    context = JSONField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def render(self, content_type='html'):
        template = Template(self.template.template)
        context = Context(self.context)
        context['reregistration'] = Reregistration.objects.get(agreement=self)
        return template.render(context)


class Sign(models.Model):
    ''' Подписи договора. '''
    key_info = models.TextField()
    signed_info = models.TextField()
    signature_value = models.TextField()
    agreement = models.ForeignKey(Agreement)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Car(models.Model):
    ''' ТС. Временная модель для хранения авто (в будущем возможно использования его как временного кэша) '''
    manufacturer = models.CharField(max_length=256, default='')
    model = models.CharField(max_length=256, default='')
    user = models.CharField(max_length=20, default='')
    number = models.CharField(max_length=16, default='', blank=True)
    vin_code = models.CharField(max_length=20, default='')
    color_text = models.CharField(max_length=64, default='', blank=True)
    color_code = models.CharField(max_length=16, default='', blank=True)
    year = models.CharField(max_length=5, default='', blank=True)
    passport_number = models.CharField(max_length=64, default='', blank=True)
    engine_capacity = models.DecimalField(default=0, max_digits=5, decimal_places=3, blank=True)
    is_registred = models.BooleanField(default=True)

    def __str__(self):
        return self.manufacturer + ' ' + self.model

    def reregistration(self):
        ''' Получение текущего процесса перерегистрации ТС '''
        reregistrations = self.reregistration_set.exclude(is_number_received=True)
        return (reregistrations[0] if len(reregistrations) else None)

    def deregistration(self):
        ''' Получение текущего процесса снятия с учета ТС '''
        deregistrations = self.deregistration_set.exclude(is_success=True)
        return (deregistrations[0] if len(deregistrations) else None)


class Deregistration(models.Model):
    ''' Снятие с учета '''
    is_paid = models.BooleanField()
    is_transit_number = models.BooleanField()
    car = models.ForeignKey(Car)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_success = models.BooleanField()


class Tax(models.Model):
    ''' Налоги '''
    amount = models.DecimalField(max_digits=19, decimal_places=2)
    info = models.TextField()
    is_paid = models.BooleanField()
    car = models.ForeignKey(Car)

    class Meta:
        verbose_name_plural = "taxes"


class Fine(models.Model):
    ''' Штрафы '''
    amount = models.DecimalField(max_digits=19, decimal_places=2)
    info = models.TextField()
    is_paid = models.BooleanField()
    car = models.ForeignKey(Car)


class Reregistration(models.Model):
    ''' Перерегистрация '''
    seller = models.CharField(max_length=20, default='', blank=True)
    buyer = models.CharField(max_length=20, default='', blank=True)
    car = models.ForeignKey(Car)
    amount = models.DecimalField(max_digits=19, decimal_places=2, default=0)
    amount_text = models.CharField(max_length=256, blank=True)
    number = models.CharField(max_length=8, blank=True, default='')
    agreement = models.ForeignKey(Agreement, null=True, blank=True)
    seller_sign = models.TextField(blank=True)  # Что бы не делать лишние joinы подписи дублируются
    buyer_sign = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_tax_paid = models.BooleanField(default=False)
    is_number_received = models.BooleanField(default=False)


class Registration(models.Model):
    ''' Регистрация '''
    user = models.CharField(max_length=20)
    car_vin_code = models.CharField(max_length=20)
    document = models.CharField(max_length=512)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_paid = models.BooleanField(default=False)
    number = models.CharField(max_length=8, blank=True, default='')
    result = models.TextField()
    is_result_success = models.BooleanField(default=False)
    car = models.ForeignKey(Car, null=True)

    def upload_document(self, files):
        for file in files:
            mongo_client = MongoClient(settings.MONGO_URL)
            mongo_fs = gridfs.GridFS(mongo_client.documents)
            file_id = mongo_fs.put(file.file, filename=self.user + file.name)
            if self.document:
                self.document += '||' + str(file_id)
            else:
                self.document = str(file_id)
            self.save()

    def get_document_urls(self):
        urls = []
        for doc in self.document.split('||'):
            urls.append('/cars/document/' + doc)
        return urls


class Email(models.Model):
    iin = models.CharField(max_length=12)
    email = models.CharField(max_length=256)

src/apps/cars/views.py
import xml.etree.ElementTree as ET
import mimetypes
import xml.etree.cElementTree as ET
from datetime import datetime

from bson import ObjectId
import gridfs
from pymongo import MongoClient

from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.x509 import NameOID

from django.conf import settings
from django.db.models import Q
from django.http import JsonResponse, QueryDict, HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt


from pki.models import RevokedCertificate

from .models import Reregistration, Car, Deregistration, Registration
from .models import Agreement, Email, AgreementTemplate, Sign

from carbase.decorators import login_required
from controller.models import Center, Inspection
from numberplates.models import NumberPlate
from numberplates.views import get_number_plates


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_exempt, name='dispatch')
class CarsView(View):
    ''' Возвращает список машин физ лица, или, если есть БИН, то организации '''
    def get(self, request):
        user = request.session.get('user_organizationalUnitName')
        if not user:
            user = request.session.get('user_serialNumber')
        cars = Car.objects.filter(user=user).order_by('id')
        ''' Незаконченные перерегистрации где пользователь выступает в качестве покупателя '''
        reregistrations = Reregistration.objects.filter(buyer=user, is_number_received=False)

        template_data = {
            'cars': cars,
            'reregistrations': reregistrations,
            'owned_numbers': get_number_plates(owner_id=request.session.get('user_serialNumber')[3:]),
            'available_numbers': get_number_plates()
        }
        return render(request, 'cars/list.html', template_data)


@method_decorator(login_required, name='dispatch')
class DocumentView(View):
    def get(self, request, doc_id):
        mongo_client = MongoClient(settings.MONGO_URL)
        mongo_fs = gridfs.GridFS(mongo_client.documents)
        doc = mongo_fs.get(ObjectId(doc_id))
        response = HttpResponse(doc.read(), content_type=mimetypes.guess_type(doc.filename))
        response['Content-Disposition'] = 'attachment; filename="' + doc_id + '.' + doc.filename.split('.')[-1] + '"'
        return response


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_exempt, name='dispatch')
class RegistrationView(View):
    def get(self, request):
        user = request.session.get('user_organizationalUnitName')
        if not user:
            user = request.session.get('user_serialNumber')
        try:
            registration = Registration.objects.get(user=user)
        except Registration.DoesNotExist:
            registration = None
        template_data = {
            'registration': registration,
            'owned_numbers': get_number_plates(owner_id=request.session.get('user_serialNumber')[3:]),
            'available_numbers': get_number_plates(),
            'centers': Center.objects.all(),
        }
        return render(request, 'cars/registration.html', template_data)

    def post(self, request):
        vin_code = request.POST.get('vin_code')
        manufacturer = request.POST.get('manufacturer')
        model = request.POST.get('model')
        year = request.POST.get('year')
        if request.session.get('user_organizationalUnitName'):
            user = request.session.get('user_organizationalUnitName')
        else:
            user = request.session.get('user_serialNumber')
        car = Car.objects.create(model=model, manufacturer=manufacturer, year=year, vin_code=vin_code, user=user)
        try:
            registration = Registration.objects.get(user=user, car_vin_code=vin_code, car=car)
        except Registration.DoesNotExist:
            registration = Registration.objects.create(user=user, car_vin_code=vin_code, car=car)
        registration.upload_document(request.FILES.getlist('documents'))
        document_urls = registration.get_document_urls()
        return JsonResponse({'registration_id': registration.id, 'document_urls': document_urls})

    def put(self, request):
        request.PUT = QueryDict(request.body)
        registration_id = request.PUT.get('registrationId')
        registration = Registration.objects.get(id=registration_id)
        if request.PUT.get('is_tax_paid'):
            registration.is_tax_paid = True
        if request.PUT.get('inspectionDate'):
            inspections = Inspection.objects.filter(registration=registration)
            if len(inspections):
                inspection = inspections[0]
            else:
                inspection = Inspection.objects.create(registration=registration)
            inspection.time_range = request.PUT.get('inspectionTimeRange')
            inspection.center_id = request.PUT.get('inspectionCenterId')
            inspection.date = request.PUT.get('inspectionDate')
            inspection.save()
            return JsonResponse({
                'registration_id': registration.id,
                'time': inspection.time
            })
        if request.PUT.get('number'):
            number = request.PUT.get('number')
            if number != 'RANDOM':
                number = NumberPlate.objects.get(id=number)
            registration.number = str(number)
        registration.save()
        return JsonResponse({
            'registration_id': registration.id,
        })


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_exempt, name='dispatch')
class DeregistrationView(View):
    def get(self, request):
        user = request.session.get('user_organizationalUnitName')
        if not user:
            user = request.session.get('user_serialNumber')
        car_id = request.GET.get('car')
        try:
            deregistration = Deregistration.objects.get(car=car_id)
        except Deregistration.DoesNotExist:
            deregistration = None
        context = {
            'deregistration': deregistration,
            'centers': Center.objects.all(),
            'car_id': car_id
        }
        return render(request, 'cars/deregistration.html', context)

    def post(self, request):
        car = Car.objects.get(id=request.POST.get('car_id'))
        exist_degistrations = Deregistration.objects.filter(car=car)
        if exist_degistrations:
            deregistration = exist_degistrations[0]
            deregistration.is_transit_number = bool(int(request.POST.get('is_transit_number')))
            deregistration.is_paid = bool(int(request.POST.get('is_paid', '0')))
            deregistration.save()
        else:
            deregistration = Deregistration.objects.create(
                is_transit_number=bool(int(request.POST.get('is_transit_number'))),
                car=car,
                is_paid=bool(int(request.POST.get('is_paid', '0'))),
                is_success=False
            )
        return JsonResponse({'deregistration_id': deregistration.id, 'car_id': deregistration.car.id})

    def put(self, request):
        request.PUT = QueryDict(request.body)
        deregistration_id = request.PUT.get('deregistrationId')
        deregistration = Deregistration.objects.get(id=deregistration_id)
        if request.PUT.get('inspectionDate'):
            inspections = Inspection.objects.filter(deregistration=deregistration)
            if len(inspections):
                inspection = inspections[0]
            else:
                inspection = Inspection.objects.create(deregistration=deregistration)
            inspection.time_range = request.PUT.get('inspectionTimeRange')
            inspection.center_id = request.PUT.get('inspectionCenterId')
            inspection.date = request.PUT.get('inspectionDate')
            inspection.save()
            return JsonResponse({
                'deregistration_id': deregistration.id,
                'time': inspection.time
            })
        return JsonResponse({'deregistration_id': deregistration.id, 'car_id': deregistration.car.id})


@method_decorator(login_required, name='dispatch')
@method_decorator(csrf_exempt, name='dispatch')
class ReregistrationView(View):
    def get(self, request):
        user = request.session.get('user_organizationalUnitName')
        if not user:
            user = request.session.get('user_serialNumber')
        car_id = request.GET.get('car')

        try:
            reregistration = Reregistration.objects.get(car=car_id, is_number_received=False)
        except Reregistration.DoesNotExist:
            reregistration = None

        if request.GET.get('side') == 'seller':
            agreements = AgreementTemplate.objects.filter(Q(owner=user) | Q(owner=None))
            context = {'reregistration': reregistration, 'agreements': agreements, 'car_id': car_id}
            return render(request, 'cars/reregistration_seller.html', context)
        else:
            context = {
                'owned_numbers': get_number_plates(owner_id=request.session.get('user_serialNumber')[3:]),
                'available_numbers': get_number_plates(),
                'reregistration': reregistration,
                'centers': Center.objects.all()
            }
            return render(request, 'cars/reregistration_buyer.html', context)

    def post(self, request):
        ''' Создания нового процесса перерегистрации '''
        car_id = request.POST.get('car_id')
        car = Car.objects.get(id=car_id)
        if request.session.get('user_organizationalUnitName'):
            seller = request.session.get('user_organizationalUnitName')
        else:
            seller = request.session.get('user_serialNumber')
        buyer = request.POST.get('buyer')
        agreement_id = request.POST.get('agreement')

src/templates/cars/list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load cars_filters %}
{% load qr_tags %}

{% block title %}Мои машины{% endblock %}
{% block styles %}
  <link href="{% static 'css/cars.css' %}" rel="stylesheet">
  <link href="{% static 'css/numbers.css' %}" rel="stylesheet">
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/pki.js' %}"></script>
  <script src="{% static 'js/cars.js' %}"></script>
  <script src="{% static 'js/numbers.js' %}"></script>
  <script>
    // Название куки
    var cookie = 'enjoyhint_cars';
    // Селектор панели - по умолчанию панель 1
    // Если панель есть, то продолжаем
    if ( $('#carPanel1').length > 0 ) {
      // Проверяем есть ли кука, если нет запускаем hint
      if (!getCookie(cookie)) {
        // Создаем куку
        setCookie(cookie, 1, 60, 'cars');
        // Проверим регистрацию ТС
        var is_reg = false;
        if( $('#hintdereg1').length > 0 ) { is_reg = true; }
        // Работа с enjoyhint
        var enjoyhint_instance = new EnjoyHint({});
        var enjoyhint_script_steps = [
          {
            selector: '#carPanel1',
            event: 'click',
            description: 'Начало работы',
            showNext: true,
            nextButton: { text: 'Далее' },
            skipButton: { text: 'ОК' }
          },
          {
            selector: '#hintfine1',
            event: 'click',
            description: 'Проверьте и оплатите штрафы',
            showNext: true,
            nextButton: { text: 'Далее' },
            skipButton: { text: 'ОК' }
          },
          {
            selector: '#hinttax1',
            event: 'click',
            description: 'Проверьте и оплатите налоги',
            showNext: true,
            nextButton: { text: 'Далее' },
            skipButton: { text: 'ОК' }
          },
          {
            selector: '#hintrereg1',
            event: 'click',
            description: 'Пройдите перерегистрация авто',
            showNext: (is_reg) ? true : false,
            nextButton: { text: 'Или' },
            skipButton: { text: 'ОК' }
          }
        ];
        if(is_reg) {
          enjoyhint_script_steps.push({
            selector: '#hintdereg1',
            event: 'click',
            description: 'Снимите с учета',
            skipButton: { text: 'ОК' }
          });
        }
        enjoyhint_instance.set(enjoyhint_script_steps);
        enjoyhint_instance.run();
      }
    }
  </script>
{% endblock %}


{% block content %}
  {% include 'includes/header.html' with reregistrations=reregistrations %}
  <div class="container cars">
    {% for car in cars %}
      {% with car_taxes=car.tax_set.all car_fines=car.fine_set.all %}
        <div class="car col-xs-6" id="carPanel{{car.id}}">
          <div class="panel {% if car.is_registred %}panel-default{% else %}panel-warning{% endif %}">
            <div class="panel-heading">
              {{ car.manufacturer }} {{car.model}}
              <span class="pull-right">{% if car.is_registred %}{{ car.number }}{% else %}Снята с учета{% endif %}</span>
            </div>
            <div class="panel-body"><i>Инфо о машине</i></div>
            <div class='panel-footer'>
              <ul class="list-group">
                <!-- id для enjoyhint - 'hintfine{{car.id}}' -->
                <li id="hintfine{{car.id}}" class="list-group-item car-action">
                  <div class="panel panel-default {% if car|is_all_fines_paid %}panel-success{% else %}panel-danger{% endif %}">
                    <div class="collapsed panel-heading" data-target="#carFine{{car.number}}" data-toggle="collapse" aria-expanded="false">
                      <div class="car-action-text">{% if car_fines|length %}Штрафы{% else %}Штрафов нет{% endif %}</div>
                    </div>
                    <div id="carFine{{car.number}}" class="panel-body panel-collapse collapse">
                      <table class="table car-fines">
                        <tbody class="table-striped table-hover">
                          {% for fine in car_fines %}
                          <tr id="fine{{fine.id}}Row" class="{% if fine.is_paid %}text-success{% else %}text-danger{% endif %}">
                            <td class='col-xs-3'>{{fine.amount}} ₸</td>
                            <td class='col-xs-9'>{{fine.info}}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </li>
                <!-- id для enjoyhint - 'hinttax{{car.id}}' -->
                <li id="hinttax{{car.id}}" class="list-group-item car-action">
                  <div class="panel panel-default {% if car|is_all_taxes_paid %}panel-success{% else %}panel-danger{% endif %}">
                    <div class="collapsed panel-heading" data-target="#carTax{{car.number}}" data-toggle="collapse" aria-expanded="false">
                      <div class="car-action-text">Налоги</div>
                    </div>
                    <div id="carTax{{car.number}}" class="panel-body panel-collapse collapse">
                      <table class="table car-taxes">
                        <tbody class="table-striped table-hover">
                          {% for tax in car_taxes %}
                          <tr id="tax{{tax.id}}Row" class="{% if tax.is_paid %}text-success{% else %}text-danger{% endif %}">
                            <td class='col-xs-3'>{{tax.amount}} ₸</td>
                            <td class='col-xs-9'>{{tax.info}}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </li>
                {% if not car|is_all_taxes_paid or not car|is_all_fines_paid %}
                  <li class="list-group-item car-action">
                    <label type="button" class="btn btn-default btn-block pay-all-button {% if car|is_all_fines_paid and car|is_all_taxes_paid %}disabled{% endif %}" {% if not car|is_all_fines_paid or not car|is_all_taxes_paid %}data-toggle="modal" data-target="#payAllModal{{car.id}}"{% endif %}>
                      Оплатить задолжность
                    </label>
                    <div id="payAllModal{{car.id}}" class="modal fade payAllModal" tabindex="-1" role="dialog">
                      <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Оплата штрафов и налогов</h4>
                          </div>
                          <div class="modal-body">
                            <div class="step_1">
                              <ul class="list-group">
                                {% for fine in car_fines %}
                                  {% if not fine.is_paid %}
                                  <li class="list-group-item list-group-item-info">
                                    <label>
                                      <div class="col-xs-1"><input type=checkbox value="fine{{ fine.id }}" checked></div>
                                      <div class="col-xs-9">{{ fine.info }}</div>
                                      <div class="col-xs-2 pay-amount">{{ fine.amount }}&nbsp;₸</div>
                                    </label>
                                  </li>
                                  {% endif %}
                                {% endfor %}
                                {% for tax in car_taxes %}
                                  {% if not tax.is_paid %}
                                  <li class="list-group-item list-group-item-info">
                                    <label>
                                      <div class="col-xs-1"><input type=checkbox value="tax{{ tax.id }}" checked></div>
                                      <div class="col-xs-9">{{ tax.info }}</div>
                                      <div class="col-xs-2 pay-amount">{{ tax.amount }}&nbsp;₸</div>
                                    </label>
                                  </li>
                                  {% endif %}
                                {% endfor %}
                                <button class="btn btn-primary btn-lg btn-block payAllModalButton">
                                  Оплатить <span class="payAllModalAmount">0</span> ₸
                                </button>
                              </ul>
                            </div>
                            <div class="step_2" style="display:none;"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                {% endif %}
                <!-- id для enjoyhint - 'hintrereg{{car.id}}' -->
                <li id="hintrereg{{car.id}}" class="list-group-item car-action">
                  <label type="button" class="btn btn-default btn-block reregistration-button {% if not car|is_all_fines_paid or not car|is_all_taxes_paid %}disabled{% endif %}" {% if car|is_all_fines_paid and car|is_all_taxes_paid %}data-toggle="modal" data-target="#reregistrationModal{{car.id}}"{% else %}data-toggle="tooltip" data-placement="bottom" title="Необходимо сначала оплатить задолжность"{% endif %}>
                    Перерегистрация авто
                  </label>
                  <div class="modal fade reregistrationModal" id="reregistrationModal{{car.id}}" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                      <div class="modal-content">
                        <div class="modal-body">
                          <iframe src="/cars/reregistration?side=seller&car={{car.id}}"></iframe>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                {% if car.is_registred %}
                <!-- id для enjoyhint - 'hintdereg{{car.id}}' -->
                <li id="hintdereg{{car.id}}" class="list-group-item car-action">
                  <label type="button" class="btn btn-default btn-block deregistration-button {% if not car|is_all_fines_paid or not car|is_all_taxes_paid %}disabled{% endif %}" {% if car|is_all_fines_paid and car|is_all_taxes_paid %}data-toggle="modal" data-target="#deregistrationModal{{car.id}}"{% else %}data-toggle="tooltip" data-placement="bottom" title="Необходимо сначала оплатить задолжность"{% endif %}>
                    Снятие с учета
                  </label>
                  <div class="modal fade deregistrationModal" id="deregistrationModal{{car.id}}" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                      <div class="modal-content">
                        <div class="modal-body">
                          <iframe src="/cars/deregistration?car={{car.id}}"></iframe>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      {% endwith %}

    {% endfor %}
    <div class="car new_reg_car col-xs-6">
      <div class="new_reg_car_button"  data-toggle="modal" data-target="#registrationModal">
        <span class="glyphicon glyphicon-plus-sign"></span><br>
        Зарегистрировать ТС
      </div>
    </div>
    <div class="modal fade registration-modal" id="registrationModal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <iframe src="/cars/registration"></iframe>
          </div>
        </div>
      </div>
    </div>
    {% for reregistration in reregistrations %}
      <div class="modal fade reregistrationModal reregistration-modal-buyer" id="reregistrationModalBuyer{{reregistration.id}}" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-body">
              <iframe src="/cars/reregistration?side=buyer&car={{reregistration.car.id}}"></iframe>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% include 'includes/footer.html' %}
{% endblock %}